# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run Python test suite

on:
- pull_request
- push

jobs:
  python_test_suite:
    name: Run Python test suite
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]  # no particular need for in-between versions
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |-
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes -V \
              grub-common \
              mtools \
              ovmf \
              xorriso
          python3 -m venv venv/
          source venv/bin/activate
          pip3 install -r requirements.txt
          pip3 check
          diff -u0 <(pip3 freeze | sed 's,_,-,g' | sort -f) <(sed -e '/^#/d' -e '/^$/d' requirements.txt | sort -f)

      - name: Run Python test suite
        run: |-
          set -x
          source venv/bin/activate
          coverage run -m pytest -v -s
          coverage report
